### ISSUE TITLE
Downsample Cityscapes dataset

### ISSUE THREAD

**Issue by feipan664** [NoelShin/PixelPick#1]
Hi author, thank you very much for sharing this repo. I want to run it on Cityscapes. And I found that I need to downsample cityscapes dataset first, as written in the text. But I haven't found any function to run this step. Could you please help to give a bit clearer explanation in this step?

**Comment by NoelShin** [comment]
Dear Fei Pan,

Thanks for your enquiry and sorry for the inconvenience. We just pushed a
modified version of cityscapes.py to the repo. That'll automatically
downsample the Cityscapes (CS) dataset and store the resized files in the
parent directory of where the original Cityscapes data is. For instance, if
the original CS is located in "/usr/data/cityscapes", then the downsampled
files will be written in "/usr/data/cityscapes_d2" if the downsampling
ratio is set 2. Once the downsampled files are made at the beginning of the
script, the training should work as on the CamVid dataset.

Please let me know if you encounter any issues. :)

Kind regards,
Gyungin

2021년 4월 21일 (수) 오전 11:14, Fei Pan ***@***.***>님이 작성:

**Comment by feipan664** [comment]
Dear Gyungin, 

Thank you so much and the problems is resolved.

Regard,
