### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by won-bae** [NoelShin/PixelPick#4]
Hi Gyungin, 
Thanks for sharing the code for such a simple but effective algorithm. while reading your paper, I came up with two questions, 

1. In 4.5 Practical deployment, you mentioned that "it takes less than 1 second on average to label the queried pixel (10s per image),..." Does this mean it takes very close to 1 second for each pixel and about 10 seconds to annotate 10 pixels for each image?

2. In Table1, you reported the number for CCT with 1.5K fine annotations and 9K weak annotations. If my understanding on CCT is correct, however, it is supposed to be 73.2. I guess 69.4 is for the case where CCT is trained only on 1.5K fine annotations and 9K unlabeled images. Could you double check this?

I look forward to hearing from you. Thank you.

**Comment by NoelShin** [comment]
Hi Won Bae, thanks for your enquiry. Regarding your questions,

(1) Yes, that's what we meant. It takes around 0.8-0.9 second per pixel on average to label on VOC2012 dataset.
(2) The authors of CCT reported two results based on the models trained with 1.5K fine annotations from the original VOC2012 dataset and 9K augmentation dataset from the SBD dataset, each with and without image-level labels from the SBD. In the paper, we reported the one trained without image-level labels, and denoted it together with other weakly-supervised methods to make the table compact. Instead, to avoid such a confusion, we added some descriptions on each method in Supplementary Material ("Methods description" section). 
 
I hope these can answer your questions.
Please let us know if you encounter any other questions! :)

Kind regards,
Gyungin

**Comment by won-bae** [comment]
Thank you for the clarification!
